FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["src/LeonardoVinciBot/LeonardoVinciBot.csproj", "src/LeonardoVinciBot/"]
RUN dotnet restore "src/LeonardoVinciBot/LeonardoVinciBot.csproj"
COPY . .
WORKDIR "/src/src/LeonardoVinciBot"
# Build first — Playwright copies playwright.sh into the build output
RUN dotnet build "LeonardoVinciBot.csproj" -c Release
# Install Chromium + its system deps using the script generated by the Playwright NuGet package
RUN bash bin/Release/net10.0/playwright.sh install chromium --with-deps
RUN dotnet publish "LeonardoVinciBot.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app

# Chromium system dependencies required at runtime
RUN apt-get update && apt-get install -y \
    libnss3 libnspr4 libdbus-1-3 libatk1.0-0 libatk-bridge2.0-0 \
    libcups2 libdrm2 libxkbcommon0 libatspi2.0-0 libxcomposite1 \
    libxdamage1 libxfixes3 libxrandr2 libgbm1 libasound2 libx11-6 \
    libxcb1 libxext6 libx11-xcb1 \
    && rm -rf /var/lib/apt/lists/*

COPY --from=build /app/publish .
# Copy the downloaded Chromium binary from the build stage
COPY --from=build /root/.cache/ms-playwright /root/.cache/ms-playwright

ENTRYPOINT ["dotnet", "LeonardoVinciBot.dll"]
